trigger:
- main

variables:
  azureServiceConnectionId: 'MINU-AZURE-CONNECTION'
  webAppName: 'lihtneApikooliks'
  vmImageName: 'ubuntu-latest'
  pythonVersion: '3.10'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      name: 'Default'
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(pythonVersion)

    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.SourcesDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        ArtifactName: 'drop'

- stage: Deploy
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: Deploy
    pool:
      vmImage: $(vmImageName)
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appType: 'webAppLinux'
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
              runtimeStack: 'PYTHON|3.10'
              startUpCommand: 'gunicorn --bind 0.0.0.0:8000 app:app'